---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 90
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**/*.css"
  - "src/**/*.js"
  - "src/**/*.jsx"
  - "lib/**/*.js"
  - "bin/**/*.js"
exclude_paths:
- dist/*
- test/*
- webpack/*
